config/routes.rb
Omrails::Application.routes.draw do
  
  devise_for :users

  root :to => 'static_pages#home'
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  

end

app/models/assets.rb
class Assets < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  def Contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>The NesT Development Studios</title>
     <%= stylesheet_link_tag    "application", :media => "all" %>
     <%= javascript_include_tag "application" %>
     <%= csrf_meta_tags %>
    </head>
    <body>
        <header>
        <header class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              <%= link_to "The NesT DS", root_path, id: "logo" %>
              <nav>
                <ul class="nav pull-right">
                    <li><%= link_to "About", about_path %></li>
					<% if user_signed_in? %>
						<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
	                    
					<% else %>
            <li><%= link_to "Contact Us", contact_path %></li>
						

<!-- 

This "Sign in" link has been hidden temporarily to push site for informational purposes only.
            <li><%= link_to "Sign In", new_user_session_path %></li>
-->


					<% end %>




                </ul>
              </nav>
            </div>
          </div>
        </header>
        <div class="container">
            <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
            <% end %>
            <%= yield %>
        </div>


        <div class ="footer">
  <small>
    An affiliate of <%= link_to "Go West Creative", "http://gwcg.com" %>
    Site by <%= link_to "Luther Moore", "#" %>
  </small>
</div>

    </body>
</html>

app/views/static_pages/about.html.erb
<div class="center hero-unit">



<img src="http://i1287.photobucket.com/albums/a626/luther_moore/TheNesT-Full450_zps12f5a5c0.png"/><br><br>



<h2>About The NesT</h2>
  <br>
<p>
	The NesT Development Studios is a full service artist development company, supplying promising artists with the resources they need to take their careers as serious musicians to the next level.  With decades of time spent working in the business, The NesT team has gathered invaluable experience and a boutique collection of industry colleagues, all of which can be used to help artists navigate the unfamiliar territory of an industry that is constantly being refashioned.
  <br><br>
	Do in large part to technology; the music industry of today is continually changing and more competitive than ever before.  While technology has yielded an abundance of new tools for new artists to work on their craft and market themselves to a global audience, it has also made it incredibly difficult for true talent to rise above the white noise of today’s artist pool and internet sensations.  Without clear direction and an adequate amount of mentorship, it is all too easy to find yourself lost in the crowd without a voice to be heard.
  <br><br>
	Founded with the mission of fostering true talent, The NesT Development Studios aims to provide a flight plan for emerging artists to take their career to new heights while guiding them along the way. The process begins with an initial consultation meant to assess the artist’s current level of experience and determine the best course of action for that individual.  From there, the team at The NesT will put together a custom “flight plan” meant to both nurture the artist’s talent and push them to reach their full potential.
</p>
  <br><br>

 
</div>
</p>

app/views/static_pages/contact.html.erb
<center>

<div class ="center hero-unit">
	<br><br><center><font size = "6", bold>The NesT Development Studios</font>
		<br>
		2248 Townsgate Rd. Suite 1
		<br>
		Westlake Village, CA 91361
		<br>
		805.557.0333
		<br>
		info@thenestds.com
		<br>
		<br>

	</font></center>

	
	<div class = "row">
		<div class = "span3">
			<img src = "http://i1287.photobucket.com/albums/a626/luther_moore/MainPic_RobinFischette-2_zps5a7d16e0.jpeg">
		</div>
		<div class = "span5">
			<font align = "left">Robin Fischette - Managing Director
			<br>
			robin@thenestds.com</font>
		</div>
	</div>

		<hr class="feature-divider" color = "black">

	<div class = "row">
		<div class = "span3">
			<img src = "http://i1287.photobucket.com/albums/a626/luther_moore/LVStunnasoutline_zpsb49e5e07.jpg">
		</div>
		<div class = "span5">
			Luther Moore - Strategic Development
			<br>
			luther@thenestds.com
		</div>
	</div>



</div>
</center>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
	
	<div class="center hero-unit">
	<h2>You are signed in!</h2>
	<br>
	<h2>Welcome to your home page.  Please take a minute to explore our great content!</h2>

		<iframe width="853" height="480" src="http://www.youtube.com/embed/HV4Dzx-oejY?rel=0" frameborder="0" allowfullscreen></iframe>

	</div>

<% else %>

<div class="center hero-unit">

	<br><img src="http://i1287.photobucket.com/albums/a626/luther_moore/website_under_constructionlittle_zps0537d193.png"/><br><br>
    <h1>Welcome to The NesT Development Studios!</h1>

    <h2>
      Where your music career takes flight
    </h2>

    <align center>	<%= link_to "Contact Us", contact_path, class: "btn btn-large btn-inverted" %> </align>

		<hr class="feature-divider" color = "black">

<h5>What is The NesT?</h5><br>
<h6>
	The NesT Development Studios is a full service artist development company, supplying promising artists with the resources they need to take their careers as serious musicians to the next level.  With decades of time spent working in the business, The NesT team has gathered invaluable experience and a boutique collection of industry colleagues, all of which can be used to help artists navigate the unfamiliar territory of an industry that is constantly being refashioned.  Founded with the mission of fostering true talent, The NesT Development Studios aims to provide a flight plan for emerging artists to take their career to new heights while guiding them along the way. The process begins with an initial consultation meant to assess the artist’s current level of experience and determine the best course of action for that individual.  From there, the team at The NesT will put together a custom “flight plan” meant to both nurture the artist’s talent and push them to reach their full potential. 
</h6>

		<hr class="feature-divider" color = "black">


<h4>So what is it you DO?</h4><br>

<h3>
	With an impressive web of resources and industry contacts, The NesT Development Studios offers career development consultation for talented entertainers and aspiring music industry professionals.  With a unique, strategic position within the entertainment industry, The NesT Development Studios often takes on the role of developing and producing television and film projects as well.  Simply put, The NesT is in the business of connecting the right talented people with the right resources and contacts to help them along the flight path of their career.  This can include a plethora of services ranging from vocal and performance coaching, to professional services like brand consultation and packaging for record labels.  Each client is unique and The NesT creates highly customized flight plans for each and every client in pursuit of creating both a challenging but nurturing experience.
</h3>



		<hr class="feature-divider" color = "black">

<h5>What is happening at The NesT right now?</h5><br>

<h6> 
	The NesT is very fortunate to be collaborating with some of the most respected musicians and executives within the music industry.  With multiple exciting projects in incubation, we are striving to bring The NesT experience to as many talented entertainers as possible.  In order to do this we are currently hard at work building a BIGGER, BETTER nest that will soon live online and reach the best talent across the globe!  For more information, click that little button and get in touch with us.  We look forward to hearing from you!
</h6>

		<hr class="feature-divider" color = "black">

<align center>	<%= link_to "Contact Us", contact_path, class: "btn btn-large btn-primary" %> </align>


<!--  This "Sign up" button has been hidden temporarily to push site for informational purposes only.

    <%= link_to "Sign up now!", new_user_registration_path, 
                                class: "btn btn-large btn-primary" %>

 -->
</div>



<% end %>